# Generated by Django 5.2.8 on 2025-12-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the leader', max_length=100)),
                ('position', models.CharField(choices=[('BITSA Chair', 'BITSA Chair'), ('BITSA Patron', 'BITSA Patron'), ('PRESIDENT', 'PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT'), ('TREASURER', 'TREASURER'), ('SECRETARY', 'SECRETARY'), ('CHAPLAIN', 'CHAPLAIN'), ('NETWORKING REPRESENTATIVE', 'NETWORKING REPRESENTATIVE'), ('SOFTWARE ENGINEERING REPRESENTATIVE', 'SOFTWARE ENGINEERING REPRESENTATIVE'), ('BBIT REPRESENTATIVE', 'BBIT REPRESENTATIVE'), ('PUBLIC RELATION OFFICER', 'PUBLIC RELATION OFFICER')], help_text='Leadership position (static title)', max_length=50)),
                ('department', models.CharField(blank=True, help_text='Department or organization', max_length=100)),
                ('student_id', models.CharField(blank=True, help_text='Student ID (for student leaders)', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='leadership/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('leadership_type', models.CharField(choices=[('top', 'Top Leadership'), ('student', 'Student Leadership')], help_text='Type of leadership', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this leader should be displayed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership',
                'verbose_name_plural': 'Leadership',
                'ordering': ['leadership_type', 'order', 'name'],
            },
        ),
    ]
